"""Included password hashing in user table

Revision ID: 282ceddd810b
Revises: 64a695e85ab5
Create Date: 2025-01-21 16:03:02.398005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '282ceddd810b'
down_revision = '64a695e85ab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
