"""Set unique values for specific cells in instalaltion modal class

Revision ID: 3d28ba1b4f77
Revises: 8c21818df609
Create Date: 2025-01-28 14:09:06.719136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d28ba1b4f77'
down_revision = '8c21818df609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installation', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['fuel_sensor_2_mac'])
        batch_op.create_unique_constraint(None, ['camera_imei'])
        batch_op.create_unique_constraint(None, ['device_sim_serial'])
        batch_op.create_unique_constraint(None, ['device_sim_phone'])
        batch_op.create_unique_constraint(None, ['fuel_sensor_1_mac'])
        batch_op.create_unique_constraint(None, ['device_sim_seal'])
        batch_op.create_unique_constraint(None, ['camera_sim_serial'])
        batch_op.create_unique_constraint(None, ['camera_sim_phone'])
        batch_op.create_unique_constraint(None, ['camera_seal_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
