"""Installation table added to list

Revision ID: 42d14fea1bf7
Revises: 56e24f6982cf
Create Date: 2025-01-27 08:35:27.594555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42d14fea1bf7'
down_revision = '56e24f6982cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installation',
    sa.Column('installation_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('support_user_id', sa.Integer(), nullable=False),
    sa.Column('technician_user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('device_imei', sa.String(length=50), nullable=True),
    sa.Column('device_sim_serial', sa.String(length=50), nullable=True),
    sa.Column('device_sim_phone', sa.String(length=20), nullable=True),
    sa.Column('device_sim_seal', sa.String(length=50), nullable=True),
    sa.Column('device_password', sa.String(length=50), nullable=True),
    sa.Column('camera_imei', sa.String(length=50), nullable=True),
    sa.Column('camera_sim_serial', sa.String(length=50), nullable=True),
    sa.Column('camera_sim_phone', sa.String(length=20), nullable=True),
    sa.Column('camera_seal_number', sa.String(length=50), nullable=True),
    sa.Column('camera_password', sa.String(length=50), nullable=True),
    sa.Column('fuel_sensor_1_mac', sa.String(length=50), nullable=True),
    sa.Column('fuel_sensor_1_password', sa.String(length=50), nullable=True),
    sa.Column('fuel_sensor_2_mac', sa.String(length=50), nullable=True),
    sa.Column('fuel_sensor_2_password', sa.String(length=50), nullable=True),
    sa.Column('add_gps_online', sa.Boolean(), nullable=True),
    sa.Column('location_check', sa.Boolean(), nullable=True),
    sa.Column('ignition_check', sa.Boolean(), nullable=True),
    sa.Column('external_battery', sa.Boolean(), nullable=True),
    sa.Column('camera_check', sa.Boolean(), nullable=True),
    sa.Column('fuel_1_check', sa.Boolean(), nullable=True),
    sa.Column('fuel_2_check', sa.Boolean(), nullable=True),
    sa.Column('plate_number', sa.String(length=50), nullable=True),
    sa.Column('nick_name', sa.String(length=50), nullable=True),
    sa.Column('driver_name', sa.String(length=100), nullable=True),
    sa.Column('tank_1_capacity', sa.Float(), nullable=True),
    sa.Column('tank_1_calibration_chart', sa.String(length=255), nullable=True),
    sa.Column('tank_1_seal_number', sa.String(length=50), nullable=True),
    sa.Column('tank_2_capacity', sa.Float(), nullable=True),
    sa.Column('tank_2_calibration_chart', sa.String(length=255), nullable=True),
    sa.Column('tank_2_seal_number', sa.String(length=50), nullable=True),
    sa.Column('gps_install_pics', sa.String(length=255), nullable=True),
    sa.Column('fuel_sensor_1_pics', sa.String(length=255), nullable=True),
    sa.Column('fuel_sensor_2_pics', sa.String(length=255), nullable=True),
    sa.Column('camera_install_pics', sa.String(length=255), nullable=True),
    sa.Column('pictures_confirmed', sa.Boolean(), nullable=True),
    sa.Column('installation_date', sa.DateTime(), nullable=True),
    sa.Column('flespi_linkage', sa.String(length=255), nullable=True),
    sa.Column('external_battery_alert', sa.Boolean(), nullable=True),
    sa.Column('idling_detect', sa.Boolean(), nullable=True),
    sa.Column('tank_1_current_volume', sa.Float(), nullable=True),
    sa.Column('tank_2_current_volume', sa.Float(), nullable=True),
    sa.Column('tank_1_drain_test_volume', sa.Float(), nullable=True),
    sa.Column('tank_2_drain_test_volume', sa.Float(), nullable=True),
    sa.Column('tank_1_refill_test_volume', sa.Float(), nullable=True),
    sa.Column('tank_2_refill_test_volume', sa.Float(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('approval', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], ),
    sa.ForeignKeyConstraint(['stage_id'], ['stage.stage_id'], ),
    sa.ForeignKeyConstraint(['support_user_id'], ['user.user_id'], ),
    sa.ForeignKeyConstraint(['technician_user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('installation_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('installation')
    # ### end Alembic commands ###
