"""Added models for customer, product and project

Revision ID: 4fad4b09e982
Revises: 282ceddd810b
Create Date: 2025-01-22 04:02:28.343296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fad4b09e982'
down_revision = '282ceddd810b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('customer_address', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_description', sa.String(length=255), nullable=False),
    sa.Column('product_fields', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('customer')
    # ### end Alembic commands ###
