"""stage added to tables

Revision ID: 56e24f6982cf
Revises: d8377e3775bd
Create Date: 2025-01-27 08:28:10.859147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56e24f6982cf'
down_revision = 'd8377e3775bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stage',
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('stage_nanme', sa.String(length=30), nullable=False),
    sa.Column('stage_description', sa.String(length=255), nullable=False),
    sa.Column('stage_fields', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('stage_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stage')
    # ### end Alembic commands ###
