"""include product_name in product column

Revision ID: 5cca355d3d57
Revises: afe5981562bc
Create Date: 2025-01-22 08:37:03.322389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cca355d3d57'
down_revision = 'afe5981562bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_nanme', sa.String(length=30), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('product_nanme')

    # ### end Alembic commands ###
