"""Making device imei entry unique to be true

Revision ID: 8c21818df609
Revises: 36f39ff1ce57
Create Date: 2025-01-28 14:07:27.526467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c21818df609'
down_revision = '36f39ff1ce57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installation', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['device_imei'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
