"""rename stage name

Revision ID: 98d8ed848e4a
Revises: 6ff04fb7931a
Create Date: 2025-01-29 07:47:21.629661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98d8ed848e4a'
down_revision = '6ff04fb7931a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage_name', sa.String(length=30), nullable=False))
        batch_op.drop_column('stage_nanme')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stage', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stage_nanme', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
        batch_op.drop_column('stage_name')

    # ### end Alembic commands ###
