"""renemaed stage_name in stage db

Revision ID: b08608f04571
Revises: 98d8ed848e4a
Create Date: 2025-01-29 07:59:48.993082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b08608f04571'
down_revision = '98d8ed848e4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installation', schema=None) as batch_op:
        batch_op.drop_constraint('installation_camera_imei_key', type_='unique')
        batch_op.drop_constraint('installation_camera_sim_phone_key', type_='unique')
        batch_op.drop_constraint('installation_device_imei_key', type_='unique')
        batch_op.drop_constraint('installation_device_sim_phone_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_installation_camera_imei'), ['camera_imei'], unique=True)
        batch_op.create_index(batch_op.f('ix_installation_camera_sim_phone'), ['camera_sim_phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_installation_device_imei'), ['device_imei'], unique=True)
        batch_op.create_index(batch_op.f('ix_installation_device_sim_phone'), ['device_sim_phone'], unique=True)
        batch_op.create_index(batch_op.f('ix_installation_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_installation_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_installation_stage_id'), ['stage_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_installation_support_user_id'), ['support_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_installation_technician_user_id'), ['technician_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_installation_technician_user_id'))
        batch_op.drop_index(batch_op.f('ix_installation_support_user_id'))
        batch_op.drop_index(batch_op.f('ix_installation_stage_id'))
        batch_op.drop_index(batch_op.f('ix_installation_project_id'))
        batch_op.drop_index(batch_op.f('ix_installation_product_id'))
        batch_op.drop_index(batch_op.f('ix_installation_device_sim_phone'))
        batch_op.drop_index(batch_op.f('ix_installation_device_imei'))
        batch_op.drop_index(batch_op.f('ix_installation_camera_sim_phone'))
        batch_op.drop_index(batch_op.f('ix_installation_camera_imei'))
        batch_op.create_unique_constraint('installation_device_sim_phone_key', ['device_sim_phone'])
        batch_op.create_unique_constraint('installation_device_imei_key', ['device_imei'])
        batch_op.create_unique_constraint('installation_camera_sim_phone_key', ['camera_sim_phone'])
        batch_op.create_unique_constraint('installation_camera_imei_key', ['camera_imei'])

    # ### end Alembic commands ###
