"""added installtion_model, stage_model, and modified product_nanme on product_model table

Revision ID: d8377e3775bd
Revises: 5cca355d3d57
Create Date: 2025-01-22 17:49:56.448753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8377e3775bd'
down_revision = '5cca355d3d57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.String(length=30), nullable=False))
        batch_op.drop_column('product_nanme')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_nanme', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
        batch_op.drop_column('product_name')

    # ### end Alembic commands ###
